name: gym_app
description: Gym App with bloc stateManagment, service locator and firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  shared_preferences: ^2.0.18
  shimmer: 2.0.0
  provider: ^6.0.5
  jiffy: ^5.0.0
  logger: ^1.3.0
  firebase_core: ^2.14.0
  firebase_auth:
  lottie: 1.4.2 #Animations
  internet_connection_checker:
  open_mail_app: ^0.4.5
  persistent_bottom_nav_bar: ^5.0.2
  qr_code_scanner: ^1.0.1
  cloud_firestore: ^4.8.3
  table_calendar_jalali:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/animations/disconnected_network.json
    - assets/icons/bottomNavIcons/
    - assets/icons/bottomNavIcons/bottomNavSelected/
    - assets/icons/bottomNavIcons/bottomNavUnSelected/

  fonts:
    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/Avenir Black.ttf
          weight: 700
        - asset: assets/fonts/Avenir Regular.ttf
          weight: 400
#        - asset: assets/fonts/Raleway-SemiBold.ttf
#          weight: 600
#          style: italic

