// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIe0DuHKT2XI8Hm6NixMFEyL4ETwSan7A',
    appId: '1:683347267510:web:589d6b6011ce970a29fb17',
    messagingSenderId: '683347267510',
    projectId: 'gymapp-28aeb',
    authDomain: 'gymapp-28aeb.firebaseapp.com',
    storageBucket: 'gymapp-28aeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIH5TszSG9rB5ugiq5MFo_p1XCg6-Gcmk',
    appId: '1:683347267510:android:eaa9ad5aea42bf1b29fb17',
    messagingSenderId: '683347267510',
    projectId: 'gymapp-28aeb',
    storageBucket: 'gymapp-28aeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlRPeWt6UFByti3c8QYZQwpP4TVlinIE',
    appId: '1:683347267510:ios:b65dcd652c3c904e29fb17',
    messagingSenderId: '683347267510',
    projectId: 'gymapp-28aeb',
    storageBucket: 'gymapp-28aeb.appspot.com',
    iosClientId: '683347267510-9453smfif1ifjoadcldv4qde285vk2le.apps.googleusercontent.com',
    iosBundleId: 'GymApp.com.team.gymApp',
  );
}
