// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNnHnvuXF6QBG3rI_yVsxFA0UJjZWsQ4E',
    appId: '1:891095379171:web:2e5d655b57b5f87eaee9d6',
    messagingSenderId: '891095379171',
    projectId: 'netro-gym',
    authDomain: 'netro-gym.firebaseapp.com',
    storageBucket: 'netro-gym.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoqbx2wHPJ2vFnWCNOMlb33PVZAEHdHY',
    appId: '1:891095379171:android:8150befb24fa11a0aee9d6',
    messagingSenderId: '891095379171',
    projectId: 'netro-gym',
    storageBucket: 'netro-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQKSHGAAkbzmQZafbr9dZcwEcNrbcNCI',
    appId: '1:891095379171:ios:46543244cdb8ca8daee9d6',
    messagingSenderId: '891095379171',
    projectId: 'netro-gym',
    storageBucket: 'netro-gym.appspot.com',
    iosClientId: '891095379171-k6c30gu4ubkeksodb23g6utufqnpv1rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
